services:
  conan-server:
    image: ghcr.io/teriyakidactyl/docker-conan-exiles-server:latest
    container_name: conan-server
    restart: unless-stopped
    stop_grace_period: 135s
    environment:
      SERVER_NAME: ${SERVER_NAME:-Teriyakolypse}
      SERVER_PLAYER_PASS: ${SERVER_PLAYER_PASS:-MySecretPassword}
      SERVER_ADMIN_PASS: ${SERVER_ADMIN_PASS:-MySecretPasswordAdmin}
      SERVER_REGION_ID: ${SERVER_REGION_ID:-1}
      SERVER_NUDITY_POLICY: ${SERVER_NUDITY_POLICY:-0}
      SERVER_PORT: ${SERVER_PORT:-7777}
      SERVER_QUERY_PORT: ${SERVER_QUERY_PORT:-27015}
      SERVER_MAX_PLAYERS: ${SERVER_MAX_PLAYERS:-40}
      STEAM_WORKSHOP_MOD_IDS: ${STEAM_WORKSHOP_MOD_IDS:-}
      STEAM_ID_ALLOW_LIST: ${STEAM_ID_ALLOW_LIST:-}
      STEAM_VALIDATE: ${STEAM_VALIDATE:-false}
      UPDATE_ON_START: ${UPDATE_ON_START:-true}
    volumes:
      - conan_world:/world
      - conan_app:/app
    ports:
      - "${SERVER_PORT:-7777}:${SERVER_PORT:-7777}/udp"
      - "${SERVER_PINGER_PORT:-7778}:${SERVER_PINGER_PORT:-7778}/udp"
      - "${SERVER_QUERY_PORT:-27015}:${SERVER_QUERY_PORT:-27015}/udp"
      - "${SERVER_PORT:-7777}:${SERVER_PORT:-7777}/tcp"
      - "25575:25575/tcp"

volumes:
  conan_world:
    name: conan_world
  conan_app:
    name: conan_app
